# if this ain't an interactive shell, bail
case $- in
    *i*) ;;
      *) return;;
esac

# source all relevant bash config files
source ~/.bash/sys.bash
source ~/.bash/aliases.bash
source ~/.bash/appearance.bash
source ~/.bash/secrets.bash
