#!/usr/bin/env bash

RESET="\033[00m"
COLOR_ARRAY=(
    "$(color bg:black)" "$(color bg:red)"
    "$(color bg:green)" "$(color bg:yellow,fg:black)"
    "$(color bg:blue)" "$(color bg:purple)"
    "$(color bg:cyan)" "$(color bg:grey)"
    "$(color bg:light_black)" "$(color bg:light_red,fg:black)"
    "$(color bg:light_green,fg:black)" "$(color bg:light_yellow,fg:black)"
    "$(color bg:light_blue,fg:black)" "$(color bg:light_purple,fg:black)"
    "$(color bg:light_cyan,fg:black)" "$(color bg:light_grey,fg:black)"
)

echo -ne "\n"
for i in {1..3}; do
    for j in {0..7}; do
        if [ $i -eq 2 ]; then
            idx=$(printf "%02d" $j)
            echo -ne "${COLOR_ARRAY[j]}   $idx   "
        else
            echo -ne "${COLOR_ARRAY[j]}        "
        fi
    done
    echo -ne "$RESET\n"
done

for i in {1..3}; do
    for j in {8..15}; do
        if [ $i -eq 2 ]; then
            idx=$(printf "%02d" $j)
            echo -ne "${COLOR_ARRAY[j]}   $idx   "
        else
            echo -ne "${COLOR_ARRAY[j]}        "
        fi
    done
    echo -ne "$RESET\n"
done
echo -ne "\n"
