#!/usr/bin/env bash

if [[ $# -eq 2 ]]; then
    remote="$1"
    branch="$2"
else
    remote="$1"
    branch=$(git rev-parse --abbrev-ref HEAD)
fi
git checkout master
git branch -D $branch
git push --delete $remote $branch
git pull --rebase origin master
